### ISSUE TITLE
module 'spotify_lyrics' has no attribute 'main'

### ISSUE THREAD

**Issue by mativ123** [goktug97/yet-another-spotify-lyrics#13]
When i try to run _spotify-lyrics_ from the terminal it just prints the following error:

> Traceback (most recent call last):
>   File "/home/mathias/.local/bin/spotify-lyrics", line 33, in <module>
>     sys.exit(load_entry_point('yet-another-spotify-lyrics==2.4.5', 'console_scripts', 'spotify-lyrics')())
>   File "/home/mathias/.local/bin/spotify-lyrics", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib/python3.9/importlib/metadata.py", line 79, in load
>     return functools.reduce(getattr, attrs, module)
> AttributeError: module 'spotify_lyrics' has no attribute 'main'

I am on manjaro with all the dependencies installed. i have tried installing it both from source and trough pip but both gave me the same error. My system is fully updated.

this is what i got when installing trough pip:

> Collecting yet-another-spotify-lyrics
>  Using cached yet-another-spotify-lyrics-2.4.5.tar.gz (15.1 MB)
> Requirement already satisfied: ueberzug in /usr/lib/python3.9/site-packages (from yet-another-spotify-lyrics) (18.1.9)
> Requirement already satisfied: lxml in /usr/lib/python3.9/site-packages (from yet-another-spotify-lyrics) (4.6.4)
> Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (from yet-another-spotify-lyrics) (2.22.0)
> Requirement already satisfied: dbus-python in ./.local/lib/python3.9/site-packages (from yet-another-spotify-lyrics) (1.2.18)
> Requirement already satisfied: beautifulsoup4 in /usr/lib/python3.9/site-packages (from yet-another-spotify-lyrics) (4.7.1)
> Requirement already satisfied: soupsieve>=1.2 in /usr/lib/python3.9/site-packages (from beautifulsoup4->yet-another-spotify-lyrics) (2.2.1)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.9/site-packages (from requests->yet-another-spotify-lyrics) (2021.10.8)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.9/site-packages (from requests->yet-another-spotify-lyrics) (3.0.4)
> Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.9/site-packages (from requests->yet-another-spotify-lyrics) (2.8)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests->yet-another-spotify-lyrics) (1.25.11)
> Requirement already satisfied: python-xlib in /usr/lib/python3.9/site-packages (from ueberzug->yet-another-spotify-lyrics) (0.31)
> Requirement already satisfied: pillow in /usr/lib/python3.9/site-packages (from ueberzug->yet-another-spotify-lyrics) (8.4.0)
> Requirement already satisfied: docopt in /usr/lib/python3.9/site-packages (from ueberzug->yet-another-spotify-lyrics) (0.6.2)
> Requirement already satisfied: attrs>=18.2.0 in /usr/lib/python3.9/site-packages (from ueberzug->yet-another-spotify-lyrics) (21.2.0)
> Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.9/site-packages (from python-xlib->ueberzug->yet-another-spotify-lyrics) (1.16.0)
> Using legacy 'setup.py install' for yet-another-spotify-lyrics, since package 'wheel' is not installed.
> Installing collected packages: yet-another-spotify-lyrics
>     Running setup.py install for yet-another-spotify-lyrics ... done
> Successfully installed yet-another-spotify-lyrics-2.4.5

**Comment by goktug97** [comment]
While changing package structure, it seems I messed up the installation. I didn't realize this. It should be fixed now. You can update it using `pip install yet-another-spotify-lyrics --upgrade`
